name: haskelladventure
version: 0.1.0.0
github: "git@github.com:webbiscuit/haskell-adventure.git"
license: BSD3
author: "WebBiscuit"
copyright: "2019 WebBiscuit"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/webbiscuit/haskell-adventure#readme>

dependencies:
  - base >= 4.7 && < 5
  - regex-pcre-builtin
  - MissingH

library:
  source-dirs: src

executables:
  haskelladventure-exe:
    main: gamebook.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskelladventure

tests:
  haskelladventure-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskelladventure
